### ISSUE TITLE
Incorporar descarga de datos

### ISSUE THREAD

**Issue by manuredovan** [rubenleon/rpttai#1]
Muy buenas,

Primeramente felicitarte por poner más accesible estos datos de RPT de TAI que nos sirven a muchos de nosotros de poder visualizar todo de manera más fácil y amigable.

Mi propuesta sería añadir descarga por CSV cada uno de los organismos por separado y una totalizada.

Muchas gracias

**Comment by rubenleon** [comment]
Hola, 

Muchas gracias por el _feedback_ 😊.

El proyecto lo tengo generado solo con Javascript, tengo que estudiar alguna librería para generar CSV. Estoy utilizado Github Pages para ahórrame el hosting. 

Un saludo.
