### ISSUE TITLE
Puestos TAI

### ISSUE THREAD

**Issue by acnp29** [rubenleon/rpttai#2]
Hola.

Lo primero de todo, decirte que esta web es muy útil e intuitiva para ver los distintos puestos TAI. ENHORABUENA!

Lo segundo, y para los que nunca hemos usado github, quería preguntarte cómo muestras solo puestos TAI de otros los que no lo son. Quizás sea porque ¿usas diferentes patrones de búsqueda en la denominación del puesto? Por ejemplo, muestra todos los puestos que en la denominación tengan parte de las siguientes cadenas: "informática", "redes", "consola", ...

Un saludo y gracias anticipadas

**Comment by rubenleon** [comment]
Hola,

Gracias por pasarte por la web, me alegra que te resulte útil.

Respecto a tu pregunta, efectivamente, el objetivo principal de la web es mostrar todos los puestos de informática disponibles en la Administración General del Estado, ya sean de la categoría TAI (C1) o GSI (A2), entre otros. Para facilitar la búsqueda, he implementado un combo que te permite filtrar por el grupo de cada puesto.

En cuanto a la identificación de plazas relacionadas con informática, utilizo patrones de búsqueda basados en términos clave como "operador de consola", "programador", "informática", etc. Además, he revisado personalmente los destinos ofertados de informática para obtener descripciones.

Un saludo y gracias.
